<?php

/**
 * @file
 * Contains farmjournal_section.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function farmjournal_section_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the farmjournal_section module.
    case 'help.page.farmjournal_section':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Farmjournal Site Sections') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function farmjournal_section_theme() {
  return [
    'farmjournal_section_block' => [
      'variables' => [
        'data' => 'Default Data'
      ],
      'template' => 'block--farmjournal-section',
    ],
  ];
}
