maxlength_block_class_field: 255
field_type: multiple_textfields
default_case: standard
allow_only_letters_and_numbers: 0
block_classes_stored: '{"trd-blk":"trd-blk","more-cat-blk":"more-cat-blk","col-sm-8":"col-sm-8","visible-xs":"visible-xs","text-center":"text-center","col-xs-12":"col-xs-12","hidden-sm":"hidden-sm","hidden-md":"hidden-md","hidden-xs":"hidden-xs","centered":"centered"}'
enable_attributes: true
enable_auto_complete: true
qty_classes_per_block: 10
items_per_page: 50
enable_special_chars: true
qty_attributes_per_block: 10
enable_id_replacement: true
weight_attributes: ''
weight_class: ''
weight_id: ''
