api_key: 6f731efee9a1cc1c44636985155e5981-us19
cron: true
batch_limit: 25
api_classname: Mailchimp\Mailchimp
test_mode: false
_core:
  default_config_hash: x8k6uOqmSHPqpp71jYGxHF3_SAs3U-Pha3YCntQIhPU
enable_connected: true
connected_id: null
connected_paths: null
