mlid:
  'menu_link_content:36164cdc-d00f-405f-bddb-2b1715cb819b':
    roles:
      - author
    access_check: false
  'menu_link_content:60a82f56-d9b4-41b6-babc-8069a494a1f1':
    roles: {  }
    access_check: false
  'menu_link_content:357214e8-128b-4fa3-bb39-be7bd2f3dc3f':
    roles: {  }
    access_check: false
  'menu_link_content:6a42b37e-7d66-4284-93a7-49dd1b417ae8':
    roles:
      - author
    access_check: false
  'menu_link_content:2f3e2427-4c74-44d7-a20d-cb765aa5c3e2':
    roles:
      - author
    access_check: false
  'menu_link_content:b2e64bbf-1644-4cab-bf7c-279c4c64c8d7':
    roles:
      - author
    access_check: false
  'menu_link_content:bb8966ea-948c-4239-a37c-062d3393f2ff':
    roles:
      - author
    access_check: false
  'menu_link_content:7e495b69-87f8-4c8e-9924-f20a32135e48':
    roles:
      - author
    access_check: false
  'menu_link_content:bd3c7e61-f439-42cb-ba74-af18e2193a1d':
    roles: {  }
    access_check: false
