fixed_header: 1
scrolltop_display: 1
bootstrap_remote_type: cdn
_core:
  default_config_hash: 5Ba57QD7msoZrStw11sVxvzj7eFrCVkNCmOJmTKQe10
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: sites/default/files/cricket_1.png
favicon:
  use_default: false
  path: sites/default/files/cricket_1.png
  mimetype: image/png
header: ''
scrolltop: ''
premium_description: ''
