smtp_on: true
smtp_host: smtp.gmail.com
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_username: cricpredictor2020@gmail.com
smtp_password: Code@2020
smtp_from: cricpredictor2020@gmail.com
smtp_fromname: CricPredictor
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: true
prev_mail_system: php_mail
_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
smtp_autotls: true
smtp_keepalive: false
smtp_timeout: 30
